[variables]
COMPOSER_ALLOW_SUPERUSER = "1"

[phases.install]
onlyIncludeFiles = ["composer.json", "composer.lock", "package.json", "package-lock.json"]
cacheDirectories = ["/root/.cache/composer", "/root/.npm"]
cmds = [
  "composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader --ignore-platform-reqs",
  "npm ci --no-audit --no-fund"
]

[phases.build]
cmds = ["npm run build"]
