services:
  - type: web
    name: LMS
    env: php
    phpVersion: "8.2"
    buildCommand: composer install --optimize-autoloader --no-dev
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    autoDeploy: true